# config for running test inferences

# Paths
data_dir: "/home/local/VANDERBILT/litz/data/imagevu/nifti/preproc/"
model_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models/0511cval/fold1/"
seg_dir: "/home/litz/data/vlsp/lobe/seg/0511cval_fold1/"
clip_dir: "/home/litz/data/vlsp/lobe/clip/0511cval_fold1/"

sample: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/clinical/sample_sex_copd_cancer.csv"
# label_dir: "/home/local/VANDERBILT/litz/data/imagevu/lobe/lvlsetsegCC/"
# log_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/logs"
# tmp_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/tmp"

# Data load
dataset: "vlsp"
image_type: "*.nii.gz"
sample_size: 500
pix_dim: !!python/tuple [1, 1, 1]
k: 1
crop_shape: !!python/tuple [96,96,96]
crop_nsamples: 4
num_workers: 3
checkpoint: null
pretrained: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models/0511cval/fold1/0511cval_best_model.pth"
window: !!python/tuple [-1024, 600]

# Hyperparams
model: "unet512"
random_seed: 2
device: "cuda:0"
batch_size: 2
lr: 0.0001
epochs: 800
val_interval: 40
checkpoint_interval: 100
include_bg_loss: False
