# masi-55 16GB Quadro RTX
# For dev training protocol
# Date:03.28.22
# CUDA_VISIBLE_DEVICES=1 python main.py Config_0228.YAML

# Metadata
config_id: "test_tune"

# Paths
data_dir: "/home/local/VANDERBILT/litz/data/imagevu/nifti/train/"
label_dir: "/home/local/VANDERBILT/litz/data/imagevu/lobe/lvlsetsegCC/"
tmp_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/tmp"
checkpoint_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/checkpoints"
model_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models"
log_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/logs"

# Data load
sample_size: 10
pix_dim: !!python/tuple [1, 1, 1]
val_ratio: 0.1
crop_shape: !!python/tuple [96,96,96]
crop_nsamples: 6
num_workers: 3
checkpoint: null
window: !!python/tuple [-1500, 600]

# Hyperparams
random_seed: 0
device: "cuda:0"
batch_size: 1
lr: 0.0001
epochs: 3
val_interval: 1
checkpoint_interval: 1
include_bg_loss: False