# masi-55 16GB Quadro RTX
# For dev training protocol
# Date:03.28.22
# CUDA_VISIBLE_DEVICES=1 python main.py Config_0228.YAML

# Metadata
config_id: 0228dev

# Paths
data_dir: "/home/local/VANDERBILT/litz/data/imagevu/nifti/train/"
label_dir: "/home/local/VANDERBILT/litz/data/imagevu/lobe/uniform_lvlsetseg/"
tmp_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/tmp"
model_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models"

# Data load
sample_size: 100
pix_dim: !!python/tuple [1, 1, 1]
val_ratio: 0.1
crop_shape: !!python/tuple [96,96,96]
crop_nsamples: 6
num_workers: 2

# Hyperparams
random_seed: 0
device: "cuda:1"
batch_size: 1
lr: 0.0001
epochs: 100
val_interval: 10


