#masi-56 16GB Quadro (Nancy's)
# Train with full dataset using Unet 256
#Date:03.14.22

# Paths
data_dir: "/home/local/VANDERBILT/litz/data/imagevu/nifti/train/"
label_dir: "/home/local/VANDERBILT/litz/data/imagevu/lobe/lvlsetsegCC/"
checkpoint_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/checkpoints"
model_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models"
log_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/logs"

# Data load
sample_size: null
pix_dim: !!python/tuple [1, 1, 1]
val_ratio: 0.1
crop_shape: !!python/tuple [96,96,96]
crop_nsamples: 6
num_workers: 3
checkpoint: null

# Hyperparams
random_seed: 1
device: "cuda:0"
batch_size: 1
lr: 0.0001
epochs: 200
val_interval: 1
checkpoint_interval: 4
include_bg_loss: True