# masi-45
# Fine tune 0327unet512 on 36 examples from LUNA16 dataset. 0327unet512 was pretrained on ~100 QA examples from VLSP
# Date:03.31.22

# Paths
data_dir: "/home/local/VANDERBILT/litz/data/luna16/preproc_train"
label_dir: "/home/local/VANDERBILT/litz/data/luna16/fixed_labels/"
checkpoint_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/checkpoints"
model_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models"
log_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/logs"
tmp_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/tmp"
test_dir: "/home/local/VANDERBILT/litz/data/luna16/preproc_test"

# Data load
dataset: "luna16"
image_type: "*.mhd"
sample_size: null
pix_dim: !!python/tuple [1, 1, 1]
val_ratio: 0.28
crop_shape: !!python/tuple [96,96,96]
crop_nsamples: 4
num_workers: 3
checkpoint: null
pretrained: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models/0327unet512/0327unet512_best_model.pth"
window: !!python/tuple [-1024, 600]

# Hyperparams
model: "unet512"
random_seed: 2
device: "cuda:0"
batch_size: 1
lr: 0.0001
epochs: 500 
val_interval: 1
checkpoint_interval: 4
include_bg_loss: False
