# masi-46 16GB Quadro RTX
# For dev training protocol
# Date:03.28.22
# CUDA_VISIBLE_DEVICES=1 python main.py Config_0228.YAML

# Metadata
config_id: '0301'

# Paths
data_dir: "/home/local/VANDERBILT/litz/data/imagevu/nifti/train/"
label_dir: "/home/local/VANDERBILT/litz/data/imagevu/lobe/lvlsetsegCC/"
checkpoint_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/checkpoints"
model_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/models"
log_dir: "/home/local/VANDERBILT/litz/github/MASILab/lobe_seg/logs"

# Data load
sample_size: ''
pix_dim: !!python/tuple [1, 1, 1]
val_ratio: 0.1
crop_shape: !!python/tuple [96,96,96]
crop_nsamples: 6
num_workers: 2
checkpoint: null

# Hyperparams
random_seed: 0
device: "cuda:1"
batch_size: 1
lr: 0.0001
epochs: 100
val_interval: 1
checkpoint_interval: 2
include_bg_loss: True
